# Generated by Cloud66 Starter
FROM ruby:2.1

RUN apt-get update -qq && apt-get install -y build-essential nodejs

#set working dir
WORKDIR /tmp

#cache bundle install
ADD Gemfile /tmp/Gemfile
ADD Gemfile.lock /tmp/Gemfile.lock
RUN bundle install

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

EXPOSE 3000
ADD . $APP_HOME
