web:
  build: .
  command: bundle exec rails s -b 0.0.0.0
  ports:
   - "3000:3000"
  links:
   - mysql
   - mysql:mysql.cloud66.local
  environment:
   - RAILS_ENV=development
   - MYSQL_USERNAME=root
   - MYSQL_ADDRESS=mysql.cloud66.local
   - MYSQL_DATABASE=rails-mysql
mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
